apiVersion: apps/v1
kind: Deployment
metadata:
  name: html-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tomcat-html
  template:
    metadata:
      labels:
        app: tomcat-html
    spec:
      containers:
      - name: tomcat-container
        image: your-dockerhub-username/tomcat-html-app:latest
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: tomcat-html-service
spec:
  type: NodePort
  selector:
    app: tomcat-html
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30008

