apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-app
  labels:
    app: deployment-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deployment-app
  template:
    metadata:
      labels:
        app: deployment-app
    spec:
      containers:
      - name: deployment-app
        image: mugeshraj/deployment_app:latest  # replace with your image
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: deployment-app-service
spec:
  selector:
    app: deployment-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort

